#:import entities entities

<Player>:
    size_hint: None, None
    size: 30, 50

    canvas.before:
        PopMatrix
        Color:
            rgba: .6, .6, .6, 1
        Rectangle:
            pos: self.pos
            size: self.size
        PushMatrix

<Ground>:
    canvas:
        Color:
            rgba: .35, .2, 0, 1
        Rectangle:
            pos: self.pos
            size: self.size
